version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: esportify_bd
      POSTGRES_USER: esportify
      POSTGRES_PASSWORD: 12345
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: